# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.3.0
FROM docker.io/library/ruby:$RUBY_VERSION-preview2-slim AS base

ENV DEFAULT_PORT=8000 \
    APP_PATH="/var/app" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle"

# Copy entrypoint scripts and give execution permissions
COPY ./development-entrypoint.sh /usr/local/bin/development-entrypoint.sh
COPY ./test-entrypoint.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/development-entrypoint.sh && chmod +x /usr/local/bin/test-entrypoint.sh

# Set working directory
WORKDIR $APP_PATH

# Install dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential curl libjemalloc2 libvips libpq-dev postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Install bundler
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Copy application code
COPY . .

# Expose the port the Rails app will run on (for development)
EXPOSE $DEFAULT_PORT

# Default command to run
ENTRYPOINT [ "bundle", "exec" ]
# CMD ["rails", "server", "-b", "0.0.0.0"]
